# Config format schema number
format_version: 4
debug: True

buffer_size: 100
data_path: "../gan_data"
num_workers: 0
batch_size: 16
lr: 0.0003
input_dim: 2
data_size: 20
test_size: 10

weight_decay: 0.0005
logit_reg_weight: 0.05
grad_penalty: 10

